version: 0.2

env:
  shell: bash
  variables:
    WEBSITE_BUCKET: static-website-example

phases:
  pre_build:
    commands:
      - aws --version
  build:
    commands:
      - aws s3 sync --debug --delete . s3://$WEBSITE_BUCKET/
