apiVersion: skaffold/v2beta16
kind: Config
metadata:
  name: cropdroid-dev
build:
  tagPolicy:
    sha256: {}
  local:
    useBuildkit: true
    concurrency: 0
  artifacts:
  
  - image: builder-cropdroid-base-ubuntu
    docker:
      dockerfile: devops/docker/builder-base/Dockerfile-ubuntu
  
  - image: builder-rocksdb-ubuntu
    docker:
      dockerfile: devops/docker/builder-rocksdb/Dockerfile-ubuntu
      buildArgs:
        CORES: 20
  
  - image: builder-cockroachdb-ubuntu
    docker:
      dockerfile: devops/docker/builder-cockroachdb/Dockerfile-ubuntu
      buildArgs:
        CORES: 20
  
  - image: builder-cropdroid-standalone-ubuntu
    docker:
      dockerfile: devops/docker/builder-cropdroid/Dockerfile-standalone
      buildArgs:
        CORES: 20
    requires:
    - image: builder-cropdroid-base-ubuntu
      alias: BASE_IMAGE

  - image: builder-cropdroid-cluster-pebble-ubuntu
    docker:
      dockerfile: devops/docker/builder-cropdroid/Dockerfile-cluster
      buildArgs:
        CORES: 20
        CLUSTER_DB: pebble
    requires:
    - image: builder-cropdroid-base-ubuntu
      alias: BASE_IMAGE
    - image: builder-rocksdb-ubuntu
      alias: ROCKSDB_IMAGE

  - image: builder-cropdroid-cluster-rocksdb-ubuntu
    docker:
      dockerfile: devops/docker/builder-cropdroid/Dockerfile-cluster
      buildArgs:
        CORES: 20
        CLUSTER_DB: rocksdb
    requires:
    - image: builder-cropdroid-base-ubuntu
      alias: BASE_IMAGE
    - image: builder-rocksdb-ubuntu
      alias: ROCKSDB_IMAGE

  - image: cropdroid-standalone-ubuntu
    docker:
      dockerfile: devops/docker/cropdroid/Dockerfile-standalone-ubuntu
      buildArgs:
        CORES: 20
        BASE_IMAGE: ubuntu:latest
    requires:
    - image: builder-cropdroid-standalone-ubuntu
      alias: STANDALONE_BUILDER
    sync:
      manual:
      - src: 'cropdroid-standalone'
        dest: /opt/cropdroid/cropdroid
  
  - image: cropdroid-cluster-pebble-ubuntu
    docker:
      dockerfile: devops/docker/cropdroid/Dockerfile-cluster-ubuntu
      buildArgs:
        CORES: 20
        BASE_IMAGE: ubuntu:latest
        CLUSTER_DB: pebble
    requires:
    - image: builder-cropdroid-cluster-pebble-ubuntu
      alias: CLUSTER_BUILDER
    - image: builder-rocksdb-ubuntu
      alias: ROCKSDB_IMAGE
    sync:
      manual:
      - src: 'cropdroid'
        dest: /opt/cropdroid/cropdroid

  - image: cropdroid-cluster-rocksdb-ubuntu
    docker:
      dockerfile: devops/docker/cropdroid/Dockerfile-cluster-ubuntu
      buildArgs:
        CORES: 20
        BASE_IMAGE: ubuntu:latest
        CLUSTER_DB: rocksdb
    requires:
    - image: builder-cropdroid-cluster-pebble-ubuntu
      alias: CLUSTER_BUILDER
    - image: builder-rocksdb-ubuntu
      alias: ROCKSDB_IMAGE
    sync:
      manual:
      - src: 'cropdroid'
        dest: /opt/cropdroid/cropdroid

  - image: cropdroid-standalone-alpine
    docker:
      dockerfile: devops/docker/cropdroid/Dockerfile-standalone-alpine
      buildArgs:
        CORES: 20
        BASE_IMAGE: alpine:latest
    requires:
    - image: builder-cropdroid-standalone-ubuntu
      alias: STANDALONE_BUILDER
    sync:
      manual:
      - src: 'cropdroid-standalone'
        dest: /opt/cropdroid/cropdroid

  - image: cropdroid-cluster-pebble-alpine
    docker:
      dockerfile: devops/docker/cropdroid/Dockerfile-cluster-alpine
      buildArgs:
        CORES: 20
        BASE_IMAGE: alpine:latest
        CLUSTER_DB: pebble
    requires:
    - image: builder-cropdroid-cluster-pebble-ubuntu
      alias: CLUSTER_BUILDER
    - image: builder-rocksdb-ubuntu
      alias: ROCKSDB_IMAGE
    sync:
      manual:
      - src: 'cropdroid'
        dest: /opt/cropdroid/cropdroid

  - image: cropdroid-cluster-rocksdb-alpine
    docker:
      dockerfile: devops/docker/cropdroid/Dockerfile-cluster-alpine
      buildArgs:
        CORES: 20
        BASE_IMAGE: alpine:latest
        CLUSTER_DB: rocksdb
    requires:
    - image: builder-cropdroid-cluster-pebble-ubuntu
      alias: CLUSTER_BUILDER
    - image: builder-rocksdb-ubuntu
      alias: ROCKSDB_IMAGE
    sync:
      manual:
      - src: 'cropdroid'
        dest: /opt/cropdroid/cropdroid

  - image: cockroachdb-ubuntu
    docker:
      dockerfile: devops/docker/cockroachdb/Dockerfile-ubuntu
      buildArgs:
        CORES: 20
        BASE_IMAGE: ubuntu:latest
    requires:
    - image: builder-cockroachdb-ubuntu
      alias: COCKROACHDB_BUILDER

  # - image: cropdroid-cockroachdb-alpine
  #   docker:
  #     dockerfile: devops/docker/cockroachdb/Dockerfile-alpine
  #     buildArgs:
  #       CORES: 20
  #       BASE_IMAGE: alpine:latest
  #   requires:
  #   - image: builder-cockroachdb-ubuntu
  #     alias: COCKROACHDB_BUILDER

deploy:
  kustomize:
    paths:
    - devops/kubernetes/cockroachdb-operator/base
    #- devops/kubernetes/cropdroid-cluster/overlays/dev
    - devops/kubernetes/cropdroid-cluster/overlays/dev-cockroachdb
    #- devops/kubernetes/cropdroid-standalone/overlays/dev

profiles:
- name: base
  deploy:
    kustomize:
      paths:
      - devops/kubernetes/cluster-local/base
- name: prod
  deploy:
    kustomize:
      paths:
      - devops/kubernetes/cluster-local/overlays/prod

portForward:
- resourceType: Service
  resourceName: cockroachdb
  port: 8080
  localPort: 8080
- resourceType: Service
  resourceName: cropdroid-lb-0
  port: 80
  localPort: 80